### ISSUE TITLE
改进的相当不错啊。👍👍👍

### ISSUE THREAD

**Issue by lianai911** [xudusheng/XDSReader#1]
我猜你是根据LSYReader和DZMeBookRead结合起来做的吧。
我也差不多，基于LSYReader的基础上，加了DZMeBookRead上的上下滚动。这两天遇到了更改字号重新计算分页性能的问题，看了你的代码，大有收获。
哈哈，方便给个联系方式，一起交流交流吗。

**Comment by xudusheng** [comment]
当然可以啊，你加我QQ：597132100，欢迎交流。
