### ISSUE TITLE
新图书无法阅读

### ISSUE THREAD

**Issue by shangcezi** [xudusheng/XDSReader#3]
您好,我在项目里添加了新的本地的epub书籍,发现读取不了,但是更改成项目自身带的《zoubianquanzhognguo》就不会出问题,请问是什么问题.ps:如果把我新添加的epub书籍名字改成《zoubianquanzhongguo》,新书籍就会读取,请问,问题出在哪里.

**Comment by xudusheng** [comment]
你的问题解决了吗？我这边没有发现你说的这个问题。
你确认两个事：1、文件是否成功添加到工程？2、文件名称是否有不合法字符？

**Comment by shangcezi** [comment]
谢谢您的回复,是我自己的问题,我xcode出问题了,重启了下,好了.
